### ISSUE TITLE
StackOverflowError When Rapidly Changing Focus

### ISSUE THREAD

**Issue by Valkryst** [Valkryst/VTerminal#112]
This error occurs when holding _Tab_ or _Shift+Tab_ and quickly switching focus between two components. The cause is unknown and it does not appear to crash the program.

```
Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
	at java.desktop/javax.swing.ArrayTable.get(ArrayTable.java:152)
	at java.desktop/javax.swing.InputMap.get(InputMap.java:124)
	at java.desktop/javax.swing.InputMap.get(InputMap.java:130)
        ...
```

**Comment by Valkryst** [comment]
An additional issue, which is probably related to this exception, can be encountered in the _Radio Button_ view on the example GUI. Both buttons are set to focusable, but only the first can be focused with _Tab_. The second can be manually clicked and it will have focus and then the error will occur as soon as you press _Tab_.

**Comment by Valkryst** [comment]
This issue seems to have been caused by setting the input map for all of the components to the `.focusInputMap` property of the component from the `UIManager`. This was originally done to resolve issues with the text-based components as they have a number of built-in key combinations that would take some time to properly replicate.

```java
component.setInputMap(JComponent.WHEN_FOCUSED, (InputMap) UIManager.get("CheckBox.focusInputMap"));
```

Manually implementing the necessary keys, rather than setting the input map from the `UIManager`, resolves the issue.

```java
component.addKeyListener(new KeyAdapter() {
	@Override
	public void keyReleased(final KeyEvent e) {
		if (!component.hasFocus()) {
			return;
		}

		switch (e.getKeyCode()) {
			case KeyEvent.VK_ENTER, KeyEvent.VK_SPACE -> {
				final var checkBox = (JCheckBox) component;
				checkBox.setSelected(!checkBox.isSelected());
			}
		}
	}
});
```
